#!/bin/sh

set -e

. /usr/share/debconf/confmodule || exit 0

if [ -s /etc/perfectcrypt/password_hash ]; then
    # What should we do if it's already
    db_input low perfectcrypt/already-configured || true
    db_go
fi

# Default value is to overwrite so it's fine to use it even
# if the question has not been asked.
db_get perfectcrypt/already-configured
what="$RET"

case "$what" in
    keep|remove)
	# No further questions need to be asked
	exit 0
    ;;
esac

while true; do
    db_input low perfectcrypt/password || true
    db_input low perfectcrypt/password-again || true
    db_go

    db_get perfectcrypt/password || true
    KILL_PASS="$RET"
    db_get perfectcrypt/password-again || true
    KILL_PASS_CONFIRMATION="$RET"

    if [ "$KILL_PASS" = "$KILL_PASS_CONFIRMATION" ]; then
	break
    fi

    db_fset perfectcrypt/password-mismatch seen false
    db_fset perfectcrypt/password seen false
    db_fset perfectcrypt/password-again seen false
    db_set perfectcrypt/password ''
    db_set perfectcrypt/password-again ''

    db_input critical perfectcrypt/password-mismatch || true
    db_go
done
