#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Copy the file that we diverted away and that does the real work
if [ -e /lib/cryptsetup/askpass.cryptsetup ]; then
    copy_exec /lib/cryptsetup/askpass.cryptsetup
fi

# Copy the password hash to recognize the kill password
if [ -e /etc/perfectcrypt/password_hash ]; then
    copy_file conffile /etc/perfectcrypt/password_hash
fi

# Copy the file of settings
if [ -e /etc/perfectcrypt/settings.cfg ]; then
    copy_file conffile /etc/perfectcrypt/settings.cfg
fi

copy_exec /usr/lib/perfectcrypt/crypt

exit 0
